name: Nx Affected CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: git fetch --no-tags --prune --depth=5 origin main
      - run: yarn format:check --base=origin/main
      - run: yarn affected:build --base=origin/main --with-deps
      - run: yarn affected:lint --base=origin/main
      - run: yarn affected:test --base=origin/main
      - run: npm i -g firebase-tools
      - run: yarn nx emulators-start & yarn affected:e2e --base=origin/main
